### ISSUE TITLE
关于BILSTM+CRF的程序错误

### ISSUE THREAD

**Issue by baiyewww** [xiaolalala/Chinese-NER#2]
您好，在跑BILSTM+CRF的时候程序出现如下错误
Traceback (most recent call last):
  File "main.py", line 126, in <module>
    main(args)
  File "main.py", line 109, in main
    framework.train(train_dataset, dev_dataset, model, labels)
  File "/home/wuyue/wuyue_demo/chineseNER/Chinese-NER-master/framework.py", line 73, in train
    loss = self.train_step(batch, model)
  File "/home/wuyue/wuyue_demo/chineseNER/Chinese-NER-master/framework.py", line 32, in train_step
    input_labels=labels
  File "/home/wuyue/anaconda3/envs/chineseNER1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wuyue/wuyue_demo/chineseNER/Chinese-NER-master/model/bilstm.py", line 64, in forward
    preds = self.crf.decode(emissions, pred_mask)
  File "/home/wuyue/wuyue_demo/chineseNER/Chinese-NER-master/model/crf.py", line 118, in decode
    self._validate(emissions, mask=mask)
  File "/home/wuyue/wuyue_demo/chineseNER/Chinese-NER-master/model/crf.py", line 154, in _validate
    raise ValueError('mask of the first timestep must all be on')
ValueError: mask of the first timestep must all be on

请问怎么解决比较好？

**Comment by xiaofei05** [comment]
https://github.com/kmkurn/pytorch-crf/issues/61 你有修改bilstm+crf 的 mask 矩阵吗

**Comment by xiaofei05** [comment]
或者是有没有长度为0的训练数据，也可能产生这个问题。
